language: node_js
node_js:
    - node
    - 12
    - 10
cache: npm
install:
    - npm install
jobs:
    include:
        - stage: deploy
          if: branch == master && !fork
          node_js: 'node' # pre-installed version
          script:
              - npx semantic-release
